[versions]
android-compileSDK = "34"
android-plugin = "9.0.0"
java = "17"
kotlin = "2.3.10"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version = "6.0.2" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
android-multiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-plugin" }
dokka = { id = "org.jetbrains.dokka-javadoc", version = "2.1.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-samReceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
gitVersion = { id = "io.github.gmazzo.gitversion", version = "1.5.1" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
moduleKind = { id = "io.github.gmazzo.modulekind" }
publicationsReport = { id = "io.github.gmazzo.publications.report", version = "1.3.3" }
